let sb=null,session=null,mode="login",installPrompt=null;
const $=x=>document.getElementById(x), has=()=>window.SUPABASE_URL&&!window.SUPABASE_URL.includes("YOUR_")&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_ANON_KEY.includes("YOUR_");
let demo={profile:{name:"Demo Student",role:"student"},timetable:[{day:"Monday",time:"09:00 AM",subject:"Python",room:"Room 204"}],assignments:[{title:"Python Mini Project",subject:"Python",due:"2026-10-06"}],notes:[],notices:[],tasks:[]};
function msg(x,ok=false){$("am").textContent=x;$("am").style.color=ok?"#25804a":"#b43e3e"}
function auth(){ $("auth").classList.remove("hide");$("app").classList.add("hide");$("nm").style.display=mode==="register"?"block":"none";msg(has()?"":"Demo mode: add Supabase settings for real shared login/data.") }
$("lt").onclick=()=>{mode="login";$("lt").className="active";$("rt").className="";auth()}
$("rt").onclick=()=>{mode="register";$("rt").className="active";$("lt").className="";auth()}
$("af").onsubmit=async e=>{e.preventDefault();let email=$("em").value.trim(),pw=$("pw").value,name=$("nm").value.trim();
 if(!has()){demo.profile.name=name||"Demo Student";start();return}
 try{let r=mode==="register"?await sb.auth.signUp({email,password:pw,options:{data:{full_name:name}}}):await sb.auth.signInWithPassword({email,password:pw});if(r.error)throw r.error;session=r.data.session;if(session)start();else msg("Account created. Check email if confirmation is enabled.",true)}catch(e){msg(e.message)}};
async function profile(){if(!has())return demo.profile;let r=await sb.from("profiles").select("*").eq("id",session.user.id).single();return r.data||{name:session.user.email.split("@")[0],role:"student"}}
async function data(table){if(!has())return demo[table]||[];let r=await sb.from(table).select("*").order("created_at",{ascending:false});return r.data||[]}
async function start(){ $("auth").classList.add("hide");$("app").classList.remove("hide");let p=await profile();$("role").textContent=p.role==="owner"?"Owner":"Student";$("role").className="badge "+(p.role==="owner"?"owner":"");render("dashboard")}
document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-p]").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.p);$("side").classList.remove("open")});
async function render(p){$("date").textContent=new Date().toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long"});$("title").textContent=p[0].toUpperCase()+p.slice(1);if(p==="dashboard")dashboard();else if(p==="timetable")timetable();else if(p==="assignments")assignments();else if(p==="notes")notes();else if(p==="notices")notices();else if(p==="polls")polls();else if(p==="tasks")tasks();else profilePage()}
async function dashboard(){let p=await profile(),tt=await data("timetable"),a=await data("assignments"),n=await data("notices");$("content").innerHTML=`<div class="hero"><h2>Welcome back, ${p.name} 👋</h2><p>Everything students need, in one place.</p></div><div class="stats"><div class="card stat">📅<small>Classes</small><b>${tt.length}</b></div><div class="card stat">📝<small>Assignments</small><b>${a.length}</b></div><div class="card stat">🔔<small>Notices</small><b>${n.length}</b></div><div class="card stat">👥<small>Account</small><b>${p.role}</b></div></div><div class="layout"><div class="card"><h3>📅 Timetable</h3>${tt.slice(0,5).map(x=>`<div class="item"><div><b>${x.subject}</b><div class="muted">${x.day} · ${x.time} · ${x.room||""}</div></div></div>`).join("")||"<p class=muted>No timetable yet.</p>"}</div><div class="card"><h3>🔔 Notices</h3>${n.slice(0,5).map(x=>`<div class=item><div><b>${x.title}</b><div class=muted>${x.text}</div></div></div>`).join("")||"<p class=muted>No notices yet.</p>"}</div></div>`}
async function timetable(){let p=await profile(),d=await data("timetable");$("content").innerHTML=`<div class=card><h3>Shared Timetable ${p.role==="owner"?`<button onclick="addTT()">+ Add</button>`:""}</h3>${d.map(x=>`<div class=item><div><b>${x.subject}</b><div class=muted>${x.day} · ${x.time} · ${x.room||""}</div></div>${p.role==="owner"?`<button class=danger onclick="del('timetable','${x.id}')">Delete</button>`:""}</div>`).join("")||"<p class=muted>No timetable published.</p>"}</div>`}
async function assignments(){let p=await profile(),d=await data("assignments");$("content").innerHTML=`<div class=card><h3>Shared Assignments ${p.role==="owner"?`<button onclick="addAS()">+ Add</button>`:""}</h3>${d.map(x=>`<div class=item><div><b>${x.title}</b><div class=muted>${x.subject||""} · Due ${x.due||""}</div></div>${p.role==="owner"?`<button class=danger onclick="del('assignments','${x.id}')">Delete</button>`:""}</div>`).join("")||"<p class=muted>No assignments published.</p>"}</div>`}
async function notes(){let d=await data("notes");$("content").innerHTML=`<div class=card><h3>📚 Shared Notes <button onclick="addNote()">+ Add</button></h3>${d.map(x=>`<div class=item><div><b>${x.title}</b><div class=muted>${x.subject||""}</div><p>${x.text||""}</p></div></div>`).join("")||"<p class=muted>No notes yet.</p>"}</div>`}
async function notices(){let p=await profile(),d=await data("notices");$("content").innerHTML=`<div class=card><h3>🔔 Notices ${p.role==="owner"?`<button onclick="addNotice()">+ Publish</button>`:""}</h3>${d.map(x=>`<div class=item><div><b>${x.title}</b><div class=muted>${x.text}</div></div>${p.role==="owner"?`<button class=danger onclick="del('notices','${x.id}')">Delete</button>`:""}</div>`).join("")||"<p class=muted>No notices yet.</p>"}</div>`}
async function polls(){let d=await data("polls");$("content").innerHTML=`<div class=card><h3>🗳️ Class Polls</h3>${d.map(x=>`<div class=item><b>${x.question}</b><span>${(x.options||[]).join(" · ")}</span></div>`).join("")||"<p class=muted>No polls yet.</p>"}</div>`}
async function tasks(){let d=has()?await data("tasks"):demo.tasks;$("content").innerHTML=`<div class=card><h3>✅ My Tasks <button onclick="addTask()">+ Add</button></h3>${d.map((x,i)=>`<div class=item><label><input type=checkbox ${x.done?"checked":""} onchange="taskDone('${x.id??i}')"> ${x.text}</label></div>`).join("")||"<p class=muted>No tasks.</p>"}</div>`}
async function profilePage(){let p=await profile();$("content").innerHTML=`<div class=card><h3>👤 My Profile</h3><div class=item><b>Name</b><span>${p.name}</span></div><div class=item><b>Role</b><span class=badge>${p.role}</span></div><div class=item><b>Email</b><span>${session?.user?.email||"Demo"}</span></div></div>`}
async function addTT(){let day=prompt("Day"),time=prompt("Time"),subject=prompt("Subject"),room=prompt("Room");if(has())await sb.from("timetable").insert({day,time,subject,room});else demo.timetable.push({day,time,subject,room});render("timetable")}
async function addAS(){let title=prompt("Assignment"),subject=prompt("Subject"),due=prompt("Due YYYY-MM-DD");if(has())await sb.from("assignments").insert({title,subject,due});else demo.assignments.push({title,subject,due});render("assignments")}
async function addNote(){let title=prompt("Title"),subject=prompt("Subject"),text=prompt("Note");if(has())await sb.from("notes").insert({title,subject,text});else demo.notes.push({title,subject,text});render("notes")}
async function addNotice(){let title=prompt("Notice title"),text=prompt("Message");if(has())await sb.from("notices").insert({title,text});else demo.notices.push({title,text});render("notices")}
async function addTask(){let text=prompt("Task");if(!text)return;if(has())await sb.from("tasks").insert({user_id:session.user.id,text,done:false});else demo.tasks.push({text,done:false});render("tasks")}
async function taskDone(id){if(has()){let r=await sb.from("tasks").select("done").eq("id",id).single();await sb.from("tasks").update({done:!r.data.done}).eq("id",id)}else{let x=demo.tasks[id];if(x)x.done=!x.done}render("tasks")}
async function del(t,id){if(!confirm("Delete?"))return;if(has())await sb.from(t).delete().eq("id",id);render(t==="timetable"?"timetable":t==="assignments"?"assignments":"notices")}
$("logout").onclick=async()=>{if(has())await sb.auth.signOut();else location.reload()};$("menu").onclick=()=>$("side").classList.toggle("open");$("dark").onclick=()=>document.documentElement.classList.toggle("dark");
addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("install").style.display="block";$("ia").style.display="block"});async function install(){if(installPrompt){installPrompt.prompt();installPrompt=null}else alert("Chrome menu → Add to Home screen");}$("install").onclick=install;$("ia").onclick=install;
if(has()){sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);sb.auth.getSession().then(r=>{session=r.data.session;if(session)start();else auth()});sb.auth.onAuthStateChange((_,s)=>{session=s;if(!s)auth()})}else auth();
